FROM node:18-bullseye

# Instala todas as bibliotecas exigidas pelo Chromium/Puppeteer
RUN apt-get update && \
    apt-get install -y \
    openssl \
    libssl1.1 \
    ca-certificates \
    fonts-liberation \
    libappindicator3-1 \
    libasound2 \
    libatk-bridge2.0-0 \
    libatk1.0-0 \
    libcups2 \
    libdbus-1-3 \
    libgdk-pixbuf2.0-0 \
    libnspr4 \
    libnss3 \
    libx11-xcb1 \
    libxcomposite1 \
    libxdamage1 \
    libxrandr2 \
    libgbm1 \               
    libgtk-3-0 \            
    libxshmfence1 \         
    libxext6 \
    libxfixes3 \
    libxi6 \
    libxrender1 \
    xdg-utils \
    wget \
    --no-install-recommends && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Define a pasta de trabalho
WORKDIR /app

# Copia arquivos de depend?ncia e instala
COPY package*.json ./
RUN npm install --ignore-scripts

# Copia restante do c?digo
COPY . .

# Gera Prisma Client
RUN npx prisma generate

# (Opcional) For?a o download do Chromium
RUN npx puppeteer install

# Exp?e a porta da API
EXPOSE 3333

# Comando de desenvolvimento com hot reload
CMD ["npm", "run", "dev"]
