packages:
  - "packages/*"
  - "app"
  - "infra"
  - "services/gateway"
  - "services/organization-service"
  - "services/audit-service"
  - "shared"
  - "services/user-service"
  - "services/rh-service"
  - "services/task-service"
  - "services/client-service"
  - "services/project-service"
  - "services/department-service"
