-- CreateTable
CREATE TABLE "clients" (
    "id" TEXT NOT NULL,
    "dominio_code" TEXT,
    "name" TEXT NOT NULL,
    "company_name" TEXT,
    "fantasy_name" TEXT,
    "cnpj" TEXT NOT NULL,
    "cnae" TEXT,
    "responsible" TEXT,
    "cpf_responsible" TEXT,
    "agent" TEXT,
    "cpf_agent" TEXT,
    "number" TEXT,
    "email" TEXT,
    "address" TEXT,
    "cep" TEXT,
    "neighborhood" TEXT,
    "state" TEXT,
    "city" TEXT,
    "customer_since" TIMESTAMP(3),
    "municipal_registration" TEXT,
    "state_registration" TEXT,
    "commercial_board_registration" TEXT,
    "status" TEXT NOT NULL,
    "competence_entry" TIMESTAMP(3),
    "competence_output" TIMESTAMP(3),
    "opening_date" TIMESTAMP(3),
    "instagram" TEXT,
    "indication" TEXT,
    "regime" TEXT,
    "size" TEXT,
    "segment" TEXT,
    "contabil" TEXT,
    "fiscal" TEXT,
    "pessoal" TEXT,
    "infoproduto" TEXT,
    "consultoria" TEXT,
    "start_strike" TIMESTAMP(3),
    "end_strike" TIMESTAMP(3),
    "deletion_date" TIMESTAMP(3),
    "contract" BOOLEAN,
    "service" TEXT,
    "solucao" TEXT,
    "prospecting_status" TEXT NOT NULL,
    "date_status" TIMESTAMP(3),
    "description_prospecting" TEXT,
    "month_prospecting" TEXT,
    "register_date_prospecting" TEXT,
    "participants_meet" TEXT,
    "meet_type" TEXT,
    "closing_date" TIMESTAMP(3),

    CONSTRAINT "clients_pkey" PRIMARY KEY ("id")
);
