import type { ServiceBinding, WorkerEnv } from "@workspace/runtime";

export interface CertificateWorkerEnv extends WorkerEnv {
  JWT_SECRET: string;
  INTERNAL_SERVICE_TOKEN: string;
  CERTIFICATE_PASSWORD_ENCRYPTION_KEY: string;
  CERTIFICATE_PASSWORD_ENCRYPTION_KEY_VERSION?: string;
  CERTIFICATE_FILE_ENCRYPTION_KEY?: string;
  CERTIFICATE_FILE_ENCRYPTION_KEY_VERSION?: string;
  CERTIFICATE_STORAGE_BUCKET?: string;
  CERTIFICATE_FILE_MAX_SIZE_BYTES?: number;
  CERTIFICATE_NOTIFICATION_WINDOW_DAYS?: number;
  CERTIFICATE_REPORTING_TOKEN?: string;
  CERTIFICATE_REPORTING_GRANT_SECRET?: string;
  REPORTS_INTERNAL_TOKEN?: string;
  REPORTS_GRANT_SECRET?: string;
  SUPABASE_URL?: string;
  SUPABASE_SERVICE_ROLE_KEY?: string;
  AUDIT_SERVICE?: ServiceBinding;
}
