import assert from "node:assert/strict";
import test from "node:test";

import {
  buildGeneratedSmokeOperations,
  deriveServiceHarnessConfig,
  extractOpenApiOperationsFromSource,
  formatGeneratedSmokeModule,
  mergeServiceRegistryEntry,
} from "./service-harness-lib.mjs";

test("deriveServiceHarnessConfig creates deterministic defaults for a new service", () => {
  const config = deriveServiceHarnessConfig({
    service: "billing-service",
    port: "3040",
    usesPrisma: true,
  });

  assert.deepEqual(config, {
    name: "billing-service",
    packagePath: "services/billing-service",
    defaultUrl: "http://localhost:3040",
    urlEnvKey: "BILLING_SERVICE_URL",
    openapiSpecPath: "services/billing-service/src/openapi/spec.ts",
    authModes: ["public", "bearer"],
    internalTokenEnvKey: null,
    prismaOutputPath: "services/billing-service/src/generated/prisma",
  });
});

test("mergeServiceRegistryEntry replaces an existing service without duplicating it", () => {
  const existing = [
    { name: "gateway", packagePath: "services/gateway" },
    { name: "billing-service", packagePath: "services/billing-service", defaultUrl: "old" },
    { name: "user-service", packagePath: "services/user-service" },
  ];

  const merged = mergeServiceRegistryEntry(existing, {
    name: "billing-service",
    packagePath: "services/billing-service",
    defaultUrl: "http://localhost:3040",
  });

  assert.equal(merged.length, 3);
  assert.equal(merged.filter((entry) => entry.name === "billing-service").length, 1);
  assert.deepEqual(
    merged.map((entry) => entry.name),
    ["gateway", "billing-service", "user-service"],
  );
  assert.equal(
    merged.find((entry) => entry.name === "billing-service")?.defaultUrl,
    "http://localhost:3040",
  );
});

test("extractOpenApiOperationsFromSource discovers path operations from spec source", () => {
  const operations = extractOpenApiOperationsFromSource(`
    export const spec = {
      paths: {
        "/health": {
          get: { responses: {} },
        },
        "/billing/invoices": {
          post: { responses: {} },
          get: { responses: {} },
        },
      },
    };
  `);

  assert.deepEqual(operations, [
    { method: "GET", path: "/health" },
    { method: "POST", path: "/billing/invoices" },
    { method: "GET", path: "/billing/invoices" },
  ]);
});

test("buildGeneratedSmokeOperations creates runnable probes and route placeholders", () => {
  const config = deriveServiceHarnessConfig({
    service: "billing-service",
    port: "3040",
  });
  const discoveredOperations = [
    { method: "GET", path: "/health" },
    { method: "GET", path: "/ready" },
    { method: "POST", path: "/billing/invoices" },
  ];

  const scaffold = buildGeneratedSmokeOperations(config, discoveredOperations);

  assert.deepEqual(scaffold.operations, [
    {
      service: "billing-service",
      method: "GET",
      path: "/health",
      action: "serviceHealth",
      target: "direct",
      auth: "public",
    },
    {
      service: "billing-service",
      method: "GET",
      path: "/ready",
      action: "serviceReady",
      target: "direct",
      auth: "public",
    },
  ]);
  assert.deepEqual(scaffold.routePlaceholders, [
    {
      service: "billing-service",
      method: "POST",
      path: "/billing/invoices",
      target: "gateway",
      auth: "bearer",
      suggestedAction: "billingServicePostBillingInvoices",
    },
  ]);
});

test("formatGeneratedSmokeModule emits deterministic ESM for generated probes", () => {
  const output = formatGeneratedSmokeModule({
    service: "billing-service",
    operations: [{ service: "billing-service", method: "GET", path: "/health" }],
    routePlaceholders: [
      {
        service: "billing-service",
        method: "POST",
        path: "/billing/invoices",
        suggestedAction: "billingServicePostBillingInvoices",
      },
    ],
  });

  assert.match(output, /Generated by scripts\/generate-service-harness\.mjs/);
  assert.match(output, /export const operations = \[/);
  assert.match(output, /export const routePlaceholders = \[/);
  assert.match(output, /billingServicePostBillingInvoices/);
});
