-- Keep `version` to avoid discarding concurrency history; the prior application version safely
-- ignores this additive column. The global `users_login_key` constraint belongs to migration
-- 20260819150000_user_service_tenant_rls and must remain intact.
